feat: add support for session refresh for safari
schibsted/account-sdk-browser pull request #266
Opened 2024-01-04 16:35 UTC by hunger-programmer

ref: UUI-683

2024-01-08 08:29 UTC, bogdan-niculescu-sch approved these changes
looks good to me

2024-01-16 09:30 UTC, hunger-programmer commented on __tests__/identity.js
> +                expect(spy.mock.calls.some(c => c[0] === 'redirectToSessionService')).toBe(true);
This test can be simplified
```                expect(spy).toHaveBeenCalledTimes(1);
                expect(spy).toHaveBeenCalledWith('redirectToSessionService');```

2024-01-16 09:34 UTC, michal-oleniacz-stp commented on src/identity.js
> +                    this.emit('redirectToSessionService');
Wouldn't this event allow the brands to save any progress on critical flows to i.e. localStorage before the redirect happens?

2024-01-25 08:30 UTC, bogdan-niculescu-sch requested changes
changing to request changes to not merge by mistake since this needs to be a feature😁

2024-04-09 13:59 UTC, MichalOleniacz commented on .github/workflows/npm-publish.yml
> +                run: npm publish --access=public --tag beta #TODO: To be removed, for PoC purposes only
This should be removed

2024-04-09 14:02 UTC, michal-oleniacz-stp commented on .github/workflows/npm-publish.yml
> +                run: npm publish --access=public --tag beta #TODO: To be removed, for PoC purposes only
Beta tag should be removed for final release

2024-04-09 14:08 UTC, michal-oleniacz-stp commented on src/identity.js
> +                        const expiresIn = 1000 * (sessionData.expiresIn || 300);
In this case, `sessionData` is an object with one key "redirectURL".
We should consider creating a separate field for this.

2024-04-09 14:11 UTC, michal-oleniacz-stp commented on src/identity.js
> +                    if (this._enableSessionCaching) {
Can this "semaphore" logic be extracted into separate methods?
`hasSession` does a lot already.

2024-04-09 14:15 UTC, michal-oleniacz-stp commented on src/identity.js
> +        if (checkIfSessionOngoing)
Please remove newline before '{'

2024-04-10 13:00 UTC, merged